### ISSUE TITLE
tuneplay sounds like awful screeching on Ulanzi Pixel Clock

### ISSUE THREAD

**Issue by scarolan** [lubeda/EsphoMaTrix#114]
Hi @lubeda , i don't expect you to fix this just want to know if it's a known issue.  When I try to use tuneplay with various RTTTL ringtones it sounds more like an old school dialup modem screeching instead of a happy ringtone.

Is this a limitation of the tiny speaker in the pixel clock?  Or maybe I have something configured wrong?

Here's what I have in home assistant:

```
service: esphome.ulanzi_tuneplay
data:
  tune: 'NokiaTun:d=4,o=5,b=225:8e6,8d6,f#,g#,8c#6,8b,d,e,8b,8a,c#,e,2a'
```

and here's the config from esphome:

```
    - service: tuneplay
      variables:
        tune: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return tune;'
```
