### ISSUE TITLE
Feature Request: Update screen immediately on force screen

### ISSUE THREAD

**Issue by jd1** [lubeda/EsphoMaTrix#49]
It would be nice if the screen would update immediately when you call force screen.
E.g. I would like to show the current caller on my landline phone and it is annoying if I have to wait until the screen moves to the next to see the caller.

If you would like to keep the current behaviour, you could also split it up in two methods:
* Set next screen: This is the current behaviour of _force screen_
* Force screen: This updates the current screen immediately

It's been over half a year since I had a deeper look at the code, so I'm not sure how much effort this is. This is just an idea for an improvement, no show stopper :)

**Comment by lubeda** [comment]
Hi, take a look at the branch 2023.3.3, this should fix it!

**Comment by jd1** [comment]
That's a nice fix 👍
I didn't test it yet, but the code looks good.

**Comment by jrspowers** [comment]
hello @lubeda  if add this to the config for ulanzi it stays red it is still missing something in the config of the hold screen but can't find the service setting anywhere?

```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: $right_button_pin
      inverted: true
    on_press:
      lambda:
        id(rgb8x32)->hold_screen();
```
