### ISSUE TITLE
Export WLED effects

### ISSUE THREAD

**Issue by megane999** [lubeda/EsphoMaTrix#92]
Is it possible to export WLED effects, to show like screen saver?

**Comment by megane999** [comment]
Think about it, but WLED effects are random. GIF will be same every time

**Comment by lubeda** [comment]
Hi,
this is not part of my component! But esphome might be capable to do this without any special code. 

See https://esphome.io/components/light/index.html?highlight=e1.31 
If you disable ehmtx and activate the light component  the matrix can receive e1.31 data from wled.

**Comment by lubeda** [comment]
I didn't try wled but e1.31(https://esphome.io/components/light/index.html#e1-31-effect) works fine, this is already build in esphome.

Here is the light part of my yaml:
```yaml
light:
  - platform: neopixelbus
    id: ehmtx_light
    type: GRB
    variant: WS2812
    pin: $ledpin
    num_leds: 256
    color_correct: [30%, 30%, 30%]
    gamma_correct: 2
    name: "$devicename Light"
    restore_mode: ALWAYS_OFF
    effects:
      - e131:
          universe: 1
          channels: RGB
    on_turn_on:
      lambda: |-
         id(ehmtx_display)->set_enabled(false);
    on_turn_off:
       lambda: |-
         id(ehmtx_display)->set_enabled(true);

e131:
  method: multicast # default: register E1.31 to Multicast group

```
